formatter: "markdown"

sort:
  enabled: true
  by: required

content: |-
  <!-- markdownlint-disable -->

  {{ .Header }}

  {{ .Modules }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
